image: maven:3.6.3-jdk-11
stages:
  - build
  - sonarqube-check
  - sonarqube-vulnerability-report

build_job:
  stage: build
  tags:
    - "keyhousing"
  script:
    - mvn clean install -X

  artifacts:
    paths:
      - target/*.jar

sonarqube-check:
  stage: sonarqube-check
  tags:
    - "Swift"
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar
  only:
    - develop

sonarqube-vulnerability-report:
  stage: sonarqube-vulnerability-report
  tags:
    - "Swift"
  script:
    - 'curl -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL}/api/issues/gitlab_sast_export?projectKey=sample-java-project&branch=${CI_COMMIT_BRANCH}&pullRequest=${CI_MERGE_REQUEST_IID}" -o gl-sast-sonar-report.json'
  only:
    - develop
  artifacts:
    expire_in: 1 day
    reports:
      sast: gl-sast-sonar-report.json
  dependencies:
    - sonarqube-check
